#JWT secrets
#TODO: change to env or whatever is the storage for .pem
mp.jwt.verify.publickey.location=public.pem
mp.jwt.private-key.location=private.pem
quarkus.native.resources.includes=public.pem
mp.jwt.verify.issuer=tu-varna
mp.jwt.token.cookie=JwtToken
quarkus.http.port=8080

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true

quarkus.log.level=DEBUG

#Database configuration
#TODO: change to env
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5442/alumni_auth_service
quarkus.datasource.username=postgres
quarkus.datasource.password=alumni
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.schema-management=none

quarkus.rest-client.user-service.url=http://localhost:8082
quarkus.rest-client."com.alex.project.clients.ChatServiceRestClient".url=http://localhost:8087/chat
quarkus.rest-client."com.alex.project.clients.ChatWsRestClient".url=http://localhost:8088/chat-ws-rest
quarkus.rest-client."org.alex.project.clients.FriendServiceApiClient".url= http://localhost:8089/people

# RabbitMQ setup

# Send request
mp.messaging.outgoing.chat-message-request.connector=smallrye-rabbitmq
mp.messaging.outgoing.chat-message-request.exchange=chat-message-request
mp.messaging.outgoing.chat-message-request.routing-key=chat-message-request

# Receive response
mp.messaging.incoming.chat-message-response.connector=smallrye-rabbitmq
mp.messaging.incoming.chat-message-response.queue=chat-message-response

# RabbitMQ credentials
#TODO: change to env
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest
