#JWT secrets
smallrye.jwt.sign.key.location=classpath:privateKey.pem
smallrye.jwt.encrypt.key.location=classpath:publicKey.pem

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.issuer=${JWT_ISSUER:tu-varna}
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=JwtToken

quarkus.native.resources.includes=publicKey.pem,privateKey.pem

quarkus.http.port=${AUTH_HTTP_PORT:8080}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.csrf.enabled=false

quarkus.log.level=TRACE

# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5442}/${AUTH_DB_NAME:alumni_auth_service}
quarkus.datasource.username=${AUTH_DB_USER:postgres}
quarkus.datasource.password=${AUTH_DB_PASS:alumni}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.flyway.migrate-at-start=true

# RabbitMQ credentials
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASS:guest}

# REST clients
quarkus.rest-client.user-service.url=${USER_SERVICE_URL:http://localhost:8082}
quarkus.rest-client."com.alex.project.clients.ChatServiceRestClient".url=${CHAT_SERVICE_URL:http://localhost:8087/chat}
quarkus.rest-client."com.alex.project.clients.ChatWsRestClient".url=${WS_HANDLER_URL:http://localhost:8088/chat-ws-rest}
quarkus.rest-client."org.alex.project.clients.FriendServiceApiClient".url=${FRIEND_SERVICE_URL:http://localhost:8089/people}
quarkus.rest-client.moderation-service.url=${MODERATION_SERVICE_URL:http://localhost:8083}

# Send request
mp.messaging.outgoing.chat-message-request.connector=smallrye-rabbitmq
mp.messaging.outgoing.chat-message-request.exchange=chat-message-request
mp.messaging.outgoing.chat-message-request.routing-key=chat-message-request

# Receive response
mp.messaging.incoming.chat-message-response.connector=smallrye-rabbitmq
mp.messaging.incoming.chat-message-response.queue=chat-message-response
